### ISSUE TITLE
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

### ISSUE THREAD

**Issue by guhyeon** [MarioSimou/serverless-offline-lambda-function-urls#1]
when serverless offline start
below error fired.

OS: window
node : 18.14.0

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at ServerlessOfflineLambdaFunctionUrls.init (file:///C:/Users/guhyeon/pjt/node_modules/.pnpm/serverless-offline-lambda-function-urls@1.0.0_serverless-offline@12.0.4/node_modules/serverless-of
fline-lambda-function-urls/index.js:74:49)
    at offline:start:init (file:///C:/Users/guhyeon/pjt/node_modules/.pnpm/serverless-offline-lambda-function-urls@1.0.0_serverless-offline@12.0.4/node_modules/serverless-offline-lambda-function-
urls/index.js:11:40)
    at PluginManager.runHooks (C:\Users\guhyeon\pjt\node_modules\.pnpm\serverless@3.32.2\node_modules\serverless\lib\classes\plugin-manager.js:530:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginManager.invoke (C:\Users\guhyeon\pjt\node_modules\.pnpm\serverless@3.32.2\node_modules\serverless\lib\classes\plugin-manager.js:564:9)
    at async PluginManager.run (C:\Users\guhyeon\pjt\node_modules\.pnpm\serverless@3.32.2\node_modules\serverless\lib\classes\plugin-manager.js:604:7)
    at async Serverless.run (C:\Users\guhyeon\pjt\node_modules\.pnpm\serverless@3.32.2\node_modules\serverless\lib\serverless.js:179:5)
    at async C:\Users\guhyeon\pjt\node_modules\.pnpm\serverless@3.32.2\node_modules\serverless\scripts\serverless.js:834:9

1 deprecation found: run 'serverless doctor' for more details

**Comment by MarioSimou** [comment]
Can you provide a few more details?

1. What version of serverless are you using?
2. Can you please share your serverless.yml?

**Comment by guhyeon** [comment]
@MarioSimou sure!
I salute your sense of responsibility.

1. sls version
```
$ sls --version
Framework Core: 3.32.2 (local)
Plugin: 6.2.3
SDK: 4.3.2
```

2. serverless.yml
```
service: lambda-express
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-2'}

plugins:
  - serverless-offline
  - serverless-offline-lambda-function-urls
  - serverless-dotenv-plugin
  - serverless-plugin-monorepo

custom:
  serverless-offline:
    urlLambdaFunctionsHttpPort: 3003


# this exclude is specific to your system if your not on the same environment as Lambda
# this is added to decrease the output size to prevent size related issues
package:
  patterns:
    - '!node_modules/@tsoa/cli'
    - '!node_modules/.cache'
    - '!src/**/*'
    - '!*.eslint'
    - '!.prettierrc.js'
    - '!.eslintrc.js'
    - '!.babel.config.json'
    - '!.jest.config.js'
    - '!http'
    - '!logs/**/*'
    - '!.husky'
    - '!*.*'
    - '!.env'
    - '!.idea/**/*'

functions:
  express:
    handler: dist/src/index.handler
    url: true
```

**Comment by MarioSimou** [comment]
Can you also tell me the version of `serverless-offline`? This has been tested only with `v12.0.4`

**Comment by guhyeon** [comment]
@MarioSimou serverless-offline version is `v12.0.4`

**Comment by MarioSimou** [comment]
Hey, I have released `v1.0.1`  which may fix your issue. If my understanding is correct, your issue is related to how paths are resolved in windows platform, so I commited a change for that. Unfortunately, I couldn't test it myself because I don't have access to a windows machine, but give it try.

**Comment by guhyeon** [comment]
Unfortunately, the same problem is still occurring.
Except for changed line.

``serverless-offline-lambda-function-urls/index.js:75:12)``

**Comment by MarioSimou** [comment]
Is the issue reproducible in any of the [templates](https://github.com/MarioSimou/serverless-offline-lambda-function-urls/tree/main/templates) folders? Please pull the repo and check if the issue appears on those templates as well. If so, I can try to access a window machine and test those.

**Comment by MarioSimou** [comment]
closing this issue due to inactivity
